# Copyright (c) 2019 Graphcore Ltd. All rights reserved.

import pytest
import sys
import tempfile

from pathlib import Path
import os

sys.path.append(Path(__file__).parent.parent.as_posix())
from get_weights import get_weights  # noqa


@pytest.mark.parametrize('model_name', ['VGG16', 'VGG19', 'ResNet101'])
def test_unsupported_model(model_name):
    with pytest.raises(ValueError):
        get_weights(tempfile.gettempdir(), model_name.lower(), 'float16')


@pytest.mark.parametrize('model_name', ["MobileNet", "MobileNetV2", "NASNetMobile", "DenseNet121", "ResNet50",
                                        "Xception", "InceptionV3", "GoogleNet", "InceptionV1"])
def test_supported_model(model_name):
    KERAS_DIR = os.path.join(os.path.expanduser('~'), ".keras")
    if not os.path.exists(KERAS_DIR):
        print(f'Directory {KERAS_DIR} (generated by this test) should have been copied to CI and this is likely why it fails')
    prefix_ckpt = model_name.lower() + ".ckpt*"
    weight_path = Path(get_weights(Path(tempfile.gettempdir()), model_name.lower(), 'float16') + ".data-00000-of-00001")
    assert weight_path.exists()
    # Remove all generated files
    for files in Path(tempfile.gettempdir()).glob(prefix_ckpt):
        files.unlink()
